# Data Science Course Week 1 - Data Manipulation using Pandas

## Here we will be using real data sources to explore the features of Pandas


In [11]:
import pandas as pd

# Class Workshop

## Numpy Overview

* Why Python for Data? Numpy brings *decades* of C math into Python!
* Numpy provides a wrapper for extensive C/C++/Fortran codebases, used for data analysis functionality
* NDAarray allows easy vectorized math and broadcasting (i.e. functions for vector elements of different shapes)

In [12]:
import numpy as np

### Creating ndarrays
An array object represents a multidimensional, homogeneous array of fixed-size items.

In [13]:
a = np.array( [20,30,40,50] )
b = np.arange( 4 )
b

array([0, 1, 2, 3])

In [3]:
? np.arrange

Object `np.arrange` not found.


In [14]:
c = a-b
c

array([20, 29, 38, 47])

In [15]:
b**2

array([0, 1, 4, 9])

In [16]:
# Creating arrays
a = np.zeros((3))
b = np.ones((2,3))
c = np.random.randint(1,10,(2,3,4))

In [17]:
a

array([ 0.,  0.,  0.])

In [18]:
b

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [19]:
c

array([[[6, 4, 2, 3],
        [4, 1, 5, 1],
        [3, 1, 6, 2]],

       [[9, 7, 4, 5],
        [8, 3, 5, 3],
        [2, 6, 8, 1]]])

## Indexing, Slicing and Iterating

In [20]:
# one-dimensional arrays work like lists:
a = np.arange(10)**2

In [7]:
a

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [8]:
a[2:5]

array([ 4,  9, 16])

In [10]:
a[0:3]

array([0, 1, 4])

In [11]:
a[1:3]

array([1, 4])

### Reading Files, Selecting Columns, and Summarizing

MovieLens 100k movie rating data:
    main page: http://grouplens.org/datasets/movielens/
    data dictionary: http://files.grouplens.org/datasets/movielens/ml-100k-README.txt
    files: u.user, u.data, u.item

In [21]:
# can read a file from local computer or directly from a URL
pd.read_table('u.user', header=None)

0
0         1|24|M|technician|85711
1              2|53|F|other|94043
2             3|23|M|writer|32067
3         4|24|M|technician|43537
4              5|33|F|other|15213
5          6|42|M|executive|98101
6      7|57|M|administrator|91344
7      8|36|M|administrator|05201
8            9|29|M|student|01002
9            10|53|M|lawyer|90703
10            11|39|F|other|30329
11            12|28|F|other|06405
12         13|47|M|educator|29206
13        14|45|M|scientist|55106
14         15|49|F|educator|97301
15    16|21|M|entertainment|10309
16       17|30|M|programmer|06355
17            18|35|F|other|37212
18        19|40|M|librarian|02138
19        20|42|F|homemaker|95660
20           21|26|M|writer|30068
21           22|25|M|writer|40206
22           23|30|F|artist|48197
23           24|21|F|artist|94533
24         25|39|M|engineer|55107
25         26|49|M|engineer|21044
26        27|40|F|librarian|30030
27           28|32|M|writer|55369
28       29|41|M|programmer|94043
29           30|7|M|student|55436
..                            ...
913          914|44|F|other|08105
914  915|50|M|entertainment|60614
915       916|27|M|engineer|N2L5N
916        917|22|F|student|20006
917      918|40|M|scientist|70116
918          919|25|M|other|14216
919         920|30|F|artist|90008
920        921|20|F|student|98801
921  922|29|F|administrator|21114
922        923|21|M|student|E2E3R
923          924|29|M|other|11753
924       925|18|F|salesman|49036
925  926|49|M|entertainment|01701
926     927|23|M|programmer|55428
927        928|21|M|student|55408
928      929|44|M|scientist|53711
929      930|28|F|scientist|07310
930       931|60|M|educator|33556
931       932|58|M|educator|06437
932        933|28|M|student|48105
933       934|61|M|engineer|22902
934         935|42|M|doctor|66221
935          936|24|M|other|32789
936       937|48|M|educator|98072
937     938|38|F|technician|55038
938        939|26|F|student|33319
939  940|32|M|administrator|02215
940        941|20|M|student|97229
941      942|48|F|librarian|78209
942        943|22|M|student|77841

[943 rows x 1 columns]

Now having seen the data, read it in again but now with the pipe separator/delimiter.

In [8]:
# read 'u.user' and asign to 'users' so that we can re-use the data
user_cols = ['user_id', 'age', 'gender', 'occupation', 'zip_code']
users = pd.read_table('u.user', sep='|', header=None, names=user_cols, index_col='user_id', dtype={'zip_code':str})

NameError: name 'pd' is not defined

Now try running the example code below, uncommenting each line one at a time to see what results

In [7]:
# examine the users data

users                   # print the first 30 and last 30 rows
#type(users)             # DataFrame
#users.head()            # print the first 5 rows
#users.head(10)          # print the first 10 rows
#users.tail()            # print the last 5 rows
#users.index             # "the index" (aka "the labels")
#users.columns           # column names (which is "an index")
#users.dtypes            # data types of each column
#users.shape             # number of rows and columns
#users.values            # underlying numpy array
#users.info()            # concise summary (including memory usage)

NameError: name 'users' is not defined

Now try some of the different methods for selecting a column from a dataframe by name.

In [ ]:
# select a column

#users['gender']         # select one column
#type(users['gender'])   # Series
#users[['gender']]
#type(users[['gender']])   # DataFrame
#users.gender            # select one column using the DataFrame attribute


Now try some built in pandas methods for producing summary descriptive information from a dataframe.

In [ ]:
# summarize (describe) the data

users.describe()                    # describe all numeric columns
#users.describe(include=['object'])  # describe all object columns (can include multiple types)
#users.describe(include='all')       # describe all columns
#users.gender.describe()             # describe a single column
#users.age.mean()                    # only calculate the mean


In [ ]:
# count the number of occurrences of each value
users.occupation.value_counts()     # most useful for categorical variables
#users.age.value_counts()        # can also be used with numeric variables

# Student Exercises

## Excercise One

### Data

WHO alcohol consumption data:
    article: http://fivethirtyeight.com/datalab/dear-mona-followup-where-do-people-drink-the-most-beer-wine-and-spirits/    
    original data: https://github.com/fivethirtyeight/data/tree/master/alcohol-consumption
    file: drinks.csv (with additional 'continent' column)


In [22]:
# read drinks.csv into a DataFrame called 'drinks'
drinks = pd.read_table('drinks.csv', sep=',')
drinks = pd.read_csv('drinks.csv')              # assumes separator is comma

In [23]:
# print the head and the tail
drinks.head()
drinks.tail()

country  beer_servings  spirit_servings  wine_servings  \
188  Venezuela            333              100              3   
189    Vietnam            111                2              1   
190      Yemen              6                0              0   
191     Zambia             32               19              4   
192   Zimbabwe             64               18              4   

     total_litres_of_pure_alcohol continent  
188                           7.7        SA  
189                           2.0        AS  
190                           0.1        AS  
191                           2.5        AF  
192                           4.7        AF

In [24]:
# examine the default index, data types, and shape
drinks.index
drinks.dtypes
drinks.shape

(193, 6)

In [ ]:
# print the 'beer_servings' Series
drinks['beer_servings']
drinks.beer_servings


In [ ]:
# calculate the average 'beer_servings' for the entire dataset
drinks.describe()                   # summarize all numeric columns
drinks.beer_servings.describe()     # summarize only the 'beer_servings' Series
drinks.beer_servings.mean()         # only calculate the mean


In [ ]:

# count the number of occurrences of each 'continent' value and see if it looks correct
drinks.continent.value_counts()


#### Filtering and Sorting

using users data set again

In [ ]:
# logical filtering: only show users with age < 20
young_bool = users.age < 20         # create a Series of booleans...
users[young_bool]                   # ...and use that Series to filter rows
users[users.age < 20]               # or, combine into a single step
users[users.age < 20].occupation    # select one column from the filtered results
users[users.age < 20].occupation.value_counts()     # value_counts of resulting Series

In [ ]:
# logical filtering with multiple conditions
users[(users.age < 20) & (users.gender=='M')]       # ampersand for AND condition
users[(users.age < 20) | (users.age > 60)]          # pipe for OR condition
users[users.occupation.isin(['doctor', 'lawyer'])]  # alternative to multiple OR conditions


In [ ]:
# sorting
users.age.sort_values()                   # sort a column
users.sort_values(by='age')                   # sort a DataFrame by a single column
users.sort_values(by='age', ascending=False)  # use descending order instead
users.sort_values(by=['occupation', 'age'])   # sort by multiple columns


## Excercise Two

using the drinks dataset again and refering to the code demonstrated above, write code to answer these questions:

In [ ]:
# filter DataFrame to only include European countries

In [ ]:
# filter DataFrame to only include European countries with wine_servings > 300

In [ ]:
# calculate the average 'beer_servings' for all of Europe

In [ ]:
# determine which 10 countries have the highest total_litres_of_pure_alcohol

# Optional Excercises

### Merging Data

In [25]:
# read 'u.item' into 'movies'
movie_cols = ['movie_id', 'title']
movies = pd.read_table('u.item', sep='|', header=None, names=movie_cols, usecols=[0, 1])


In [26]:
# read 'u.data' into 'ratings'
rating_cols = ['user_id', 'movie_id', 'rating', 'timestamp']
ratings = pd.read_table('u.data', sep='\t', header=None, names=rating_cols)

In [27]:
# merge 'movies' and 'ratings' (inner join on 'movie_id')
movie_ratings = pd.merge(movies, ratings)
movies.shape
ratings.shape
movie_ratings.shape

(100000, 5)

### Grouping Data

In [31]:
movie_ratings.columns

Index(['movie_id', 'title', 'user_id', 'rating', 'timestamp'], dtype='object')

In [33]:
movie_ratings[['title', 'rating']].groupby('title').sum()

rating
title                                                     
'Til There Was You (1997)                               21
1-900 (1994)                                            13
101 Dalmatians (1996)                                  317
12 Angry Men (1957)                                    543
187 (1997)                                             124
2 Days in the Valley (1996)                            300
20,000 Leagues Under the Sea (1954)                    252
2001: A Space Odyssey (1968)                          1028
3 Ninjas: High Noon At Mega Mountain (1998)              5
39 Steps, The (1935)                                   239
8 1/2 (1963)                                           145
8 Heads in a Duffel Bag (1997)                          13
8 Seconds (1994)                                        15
A Chef in Love (1996)                                   33
Above the Rim (1994)                                    15
Absolute Power (1997)                                  428
Abyss, The (1989)                                      542
Ace Ventura: Pet Detective (1994)                      314
Ace Ventura: When Nature Calls (1995)                   99
Across the Sea of Time (1995)                           11
Addams Family Values (1993)                            245
Addicted to Love (1997)                                171
Addiction, The (1995)                                   24
Adventures of Pinocchio, The (1996)                    119
Adventures of Priscilla, Queen of the Desert, T...     399
Adventures of Robin Hood, The (1938)                   254
Affair to Remember, An (1957)                          109
African Queen, The (1951)                              636
Afterglow (1997)                                        56
Age of Innocence, The (1993)                           220
...                                                    ...
Window to Paris (1994)                                   4
Wings of Courage (1995)                                  4
Wings of Desire (1987)                                 228
Wings of the Dove, The (1997)                          276
Winnie the Pooh and the Blustery Day (1968)            285
Winter Guest, The (1997)                                31
Wishmaster (1997)                                       66
With Honors (1994)                                     141
Withnail and I (1987)                                   42
Witness (1985)                                           4
Wizard of Oz, The (1939)                              1003
Wolf (1994)                                            181
Woman in Question, The (1950)                            1
Women, The (1939)                                       55
Wonderful, Horrible Life of Leni Riefenstahl, T...      40
Wonderland (1997)                                       32
Wooden Man's Bride, The (Wu Kui) (1994)                  8
World of Apu, The (Apur Sansar) (1959)                  24
Wrong Trousers, The (1993)                             527
Wyatt Earp (1994)                                      155
Yankee Zulu (1994)                                       1
Year of the Horse (1997)                                23
You So Crazy (1994)                                      3
Young Frankenstein (1974)                              789
Young Guns (1988)                                      324
Young Guns II (1990)                                   122
Young Poisoner's Handbook, The (1995)                  137
Zeus and Roxanne (1997)                                 13
unknown                                                 31
Á köldum klaka (Cold Fever) (1994)                       3

[1664 rows x 1 columns]

### Handling Missing Values

In [ ]:
# missing values are usually excluded by default
drinks.continent.value_counts()              # excludes missing values
drinks.continent.value_counts(dropna=False)  # includes missing values

In [ ]:
# find missing values in a Series
drinks.continent.isnull()           # True if missing, False if not missing
drinks.continent.isnull().sum()     # count the missing values
drinks.continent.notnull()          # True if not missing, False if missing
drinks[drinks.continent.notnull()]  # only show rows where continent is not missing

In [ ]:
# use 'tilde' ~ to negate the boolean values
~drinks.continent.isnull()  

In [ ]:
# side note: understanding axes
drinks.sum(axis=0)      # sums "down" the 0 axis (rows)
drinks.sum()            # axis=0 is the default
drinks.sum(axis=1)      # sums "across" the 1 axis (columns)

In [ ]:
# find missing values in a DataFrame
drinks.isnull()             # DataFrame of booleans
drinks.isnull().sum()       # count the missing values in each column

In [ ]:
# fill in missing values
drinks.continent.fillna(value='NA')                 # fill in missing values with 'NA'
drinks.continent.fillna(value='NA', inplace=True)   # modifies 'drinks' in-place